In [76]:
import pandas as pd
from pandas import Series, DataFrame
import os
import locale
from locale import atof

In [77]:
print("Current working directory:", os.getcwd())

clean_data_file_path = os.path.abspath(os.path.join(os.getcwd(), 'cleaned_data'))

clean_files = os.listdir(clean_data_file_path)
clean_files

Current working directory: /Users/jennagreene/Documents/GitHub/HATCH_data

['doe_Lithium-ion battery storageTogo.csv',
 'doe_Sensible heat storageSouth Africa.csv',
 'onshore_lcoe_country.csv',
 'doe_Pumped hydro storageCanada.csv',
 'doe_Flow battery storageAustria.csv',
 'doe_Sensible heat storageChile.csv',
 'doe_Lithium-ion battery storageSenegal.csv',
 'unoosa_Rwanda.csv',
 'nemet_csp.csv',
 'ds140_Gold.csv',
 'doe_Pumped hydro storagePortugal.csv',
 'doe_Pumped hydro storageIndia.csv',
 'Caprolactam.csv',
 'doe_Flow battery storageSwitzerland.csv',
 'doe_Lead-acid battery storageTaiwan.csv',
 'unoosa_Taiwan.csv',
 'nuclear_weapons.csv',
 'solar_pv_lcoe_country.csv',
 'ds896_Aluminum.csv',
 'unoosa_Slovenia.csv',
 'doe_Pumped hydro storageThailand.csv',
 'unoosa_Slovakia.csv',
 'doe_Lithium-ion battery storageSweden.csv',
 'doe_Sodium-based battery storageCanada.csv',
 'doe_Lithium-ion battery storageNigeria.csv',
 'doe_Sodium-based battery storageItaly.csv',
 'doe_Flow battery storageRussia.csv',
 'Low-Density Polyethylene.csv',
 'Titanium Sponge.csv',
 'doe_Sodium-based battery storageUnited Kingdom.csv',
 'doe_Lead-acid battery storageSouth Africa.csv',
 'doe_Lead-acid battery storageIndia.csv',
 'doe_Flywheel battery storageSouth Korea.csv',
 'doe_Pumped hydro storageAustralia.csv',
 'doe_Hydrogen storageDenmark.csv',
 'doe_Heat thermal battery storageMorocco.csv',
 'unoosa_Denmark.csv',
 'doe_Latent heat storageCanada.csv',
 'Capillary DNA Sequencing.csv',
 'doe_Pumped hydro storageAustria.csv',
 'doe_Pumped hydro storageItaly.csv',
 'unoosa_Belarus.csv',
 'unoosa_Qatar.csv',
 'doe_Flywheel battery storageMexico.csv',
 'doe_Electro-chemical capacitorChina.csv',
 'Iron.csv',
 'doe_Flywheel battery storageCzech Republic.csv',
 'ds896_SaltProduction.csv',
 'doe_Flow battery storageJapan.csv',
 'onshore wind_lcoe.csv',
 'frame.csv',
 'wb.csv',
 'unoosa_Indonesia.csv',
 'unoosa_Lithuania.csv',
 'Computer.csv',
 'ds140_Bauxite.csv',
 'Home air conditioning.csv',
 'Nox pollution controls (boilers).csv',
 'eia2.csv',
 'chat_Steamships.csv',
 'Ethanol.csv',
 'unoosa_Philippines.csv',
 'Social media usage.csv',
 'unoosa_New Zealand.csv',
 'doe_Pumped hydro storageBulgaria.csv',
 'Processor Performance.csv',
 'doe_Pumped hydro storageJapan.csv',
 'unoosa_Morocco.csv',
 'unoosa_Angola.csv',
 'unoosa_Romania.csv',
 'bp.csv',
 'doe_Flow battery storagePortugal.csv',
 '.DS_Store',
 'doe_Compressed air energy storageSwitzerland.csv',
 'doe_Flywheel battery storageRomania.csv',
 'doe_Flow battery storageItaly.csv',
 'doe_Lithium-ion battery storageChina.csv',
 'Central heating.csv',
 'doe_Lead-acid battery storageJapan.csv',
 'li_ion_prices.csv',
 'doe_Pumped hydro storageChile.csv',
 'unoosa_Ethiopia.csv',
 'doe_Flywheel battery storageIreland.csv',
 'doe_Pumped hydro storageGermany.csv',
 'Ethylene Glycol.csv',
 'unoosa_Netherlands.csv',
 'Acrylonitrile.csv',
 'unoosa_Finland.csv',
 'doe_Heat thermal battery storageAustralia.csv',
 'unoosa_Vietnam.csv',
 'RTGS adoption.csv',
 'crude_oil_price.csv',
 'doe_Lead-acid battery storageAustralia.csv',
 'doe_Electro-chemical capacitorSouth Korea.csv',
 'unoosa_Uruguay.csv',
 'doe_Lithium-ion battery storageKenya.csv',
 'doe_Sensible heat storageIndia.csv',
 'doe_Pumped hydro storageIsrael.csv',
 'Ebook reader.csv',
 'fao_Corn Production.csv',
 'doe_Pumped hydro storageCzech Republic.csv',
 'doe_Flow battery storageIndia.csv',
 'ds140_Lead.csv',
 'doe_Pumped hydro storageSerbia.csv',
 'unoosa_Poland.csv',
 'doe_Flow battery storageAntigua and Barbuda.csv',
 'doe_Sodium-based battery storageUnited Arab Emirates.csv',
 'Podcasting.csv',
 'doe_Flywheel battery storageUnited States.csv',
 'doe_Sensible heat storageMorocco.csv',
 'Vacuum.csv',
 'ds140_SandGravelConstruction.csv',
 'doe_Pumped hydro storageFrance.csv',
 'nat_gas_price.csv',
 'Freezer.csv',
 'unoosa_Singapore.csv',
 'unoosa_Spain.csv',
 'doe_Sodium-based battery storageFrance.csv',
 'doe_Sensible heat storageItaly.csv',
 'doe_Flow battery storageGermany.csv',
 'doe_Sodium-based battery storageMartinique.csv',
 'submarine_cables.csv',
 'doe_Flow battery storageSouth Korea.csv',
 'doe_Sodium-based battery storageJapan.csv',
 'fao_Sugar Cane Production.csv',
 'unoosa_Russia.csv',
 'bts.csv',
 'ds140_Zinc.csv',
 'chat_Railroad.csv',
 'doe_Nickel-based batteryUnited States.csv',
 'unoosa_Germany.csv',
 'unoosa_Portugal.csv',
 'Nickel-Metal_Hydride_battery.csv',
 'doe_Hydrogen storageGermany.csv',
 'doe_Pumped hydro storageSwitzerland.csv',
 'doe_Pumped hydro storageIreland.csv',
 'unoosa_United Kingdom.csv',
 'doe_Flywheel battery storageGermany.csv',
 'Tablet.csv',
 'Smartphone usage.csv',
 'unoosa_Paraguay.csv',
 'chat_Crop Harvester.csv',
 'unoosa_Mongolia.csv',
 'Cyclohexane.csv',
 'doe_Flywheel battery storageUnited Kingdom.csv',
 'doe_Hydrogen storageFrance.csv',
 'hydro_price.csv',
 'doe_Lithium-ion battery storageSwitzerland.csv',
 'doe_Pumped hydro storageMorocco.csv',
 'unoosa_Italy.csv',
 'doe_Sensible heat storageSpain.csv',
 'unoosa_United States.csv',
 'doe_Sodium-based battery storageUnited States.csv',
 'Colour TV.csv',
 'Electronic ignition.csv',
 'unoosa_Thailand.csv',
 'doe_Pumped hydro storageSlovenia.csv',
 'doe_Pumped hydro storageSlovakia.csv',
 'unoosa_Laos.csv',
 'doe_Pumped hydro storageRomania.csv',
 'iiasa.csv',
 'doe_Lithium-ion battery storageGabon.csv',
 'doe_Lithium-ion battery storageUkraine.csv',
 'doe_Pumped hydro storageBosnia and Herzegovina.csv',
 'doe_Pumped hydro storageLuxembourg.csv',
 'doe_Lithium-ion battery storagePortugal.csv',
 'doe_Flywheel battery storageFrance.csv',
 'Cable TV.csv',
 'unoosa_Mauritius.csv',
 'chat_Cellphones.csv',
 'ds140_Aluminum.csv',
 'doe_Heat thermal battery storageFrance.csv',
 'ds140_CadmiumRefining.csv',
 'onshore_wind_tic_global.csv',
 'doe_Lead-acid battery storageSouth Korea.csv',
 'sodium_based_battery.csv',
 'megadams_price.csv',
 'doe_Lithium-ion battery storageFaroe Islands.csv',
 'Polyvinylchloride.csv',
 'irena.csv',
 'Radial tires.csv',
 'doe_Lithium-ion battery storageUnited Kingdom.csv',
 'doe_Compressed air energy storageUnited Kingdom.csv',
 'High-Density Polyethylene.csv',
 'unoosa_India.csv',
 'doe_Lithium-ion battery storageRussia.csv',
 'doe_Pumped hydro storageArgentina.csv',
 'doe_Flow battery storageAustralia.csv',
 'Magnetic Data Storage.csv',
 'ds896_CadmiumRefining.csv',
 'doe_Pumped hydro storageCroatia.csv',
 'unoosa_Saudi Arabia.csv',
 'doe_Pumped hydro storageSpain.csv',
 'doe_Latent heat storageUnited Kingdom.csv',
 'doe_Pumped hydro storageUnited Kingdom.csv',
 'doe_Flywheel battery storageAustralia.csv',
 'ds896_Bauxite.csv',
 'Microcomputer.csv',
 'doe_Lead-acid battery storageBrazil.csv',
 'unoosa_Brazil.csv',
 'ds140_Copper.csv',
 'doe_Lithium-ion battery storageRwanda.csv',
 'unoosa_Pakistan.csv',
 'Videocassette recorder.csv',
 'unoosa_Greece.csv',
 'doe_Lithium-ion battery storageAnguilla.csv',
 'offshore_wind_lcoe_global.csv',
 'unoosa_Bulgaria.csv',
 'doe_Flywheel battery storageCanada.csv',
 'unoosa_Egypt.csv',
 'ds140_Cement.csv',
 'Acrylic Fiber.csv',
 'doe_Lithium-ion battery storageTaiwan.csv',
 'Water Heater.csv',
 'Magnesium.csv',
 'unisd.csv',
 'Computing Growth.csv',
 'mitchell.csv',
 'doe_Lead-acid battery storageSpain.csv',
 'doe_Compressed air energy storageUnited States.csv',
 'doe_Flow battery storageDenmark.csv',
 'unoosa_Sweden.csv',
 'doe_Flywheel battery storageKenya.csv',
 'chat_Telephones.csv',
 'Vinyl Acetate.csv',
 'doe_Heat thermal battery storageChina.csv',
 'uic.csv',
 'doe_Flow battery storageSlovenia.csv',
 'Households with only mobile phones (no landlines).csv',
 'Phthalic Anhydride.csv',
 'Pentaerythritol.csv',
 'unoosa_Chile.csv',
 'Vinyl Chloride.csv',
 'doe_Heat thermal battery storageGermany.csv',
 'unoosa_Iran.csv',
 'unoosa_Sri Lanka.csv',
 'Stove.csv',
 'doe_Pumped hydro storageNorway.csv',
 'doe_Lithium-ion battery storageSouth Korea.csv',
 'Aniline.csv',
 'doe_Lithium-ion battery storageBolivia.csv',
 'doe_Lithium-ion battery storageBenin.csv',
 'ds140_Silver.csv',
 'ds896_RawSteelProduction.csv',
 'unoosa_Austria.csv',
 'Transistors per Microprocessor.csv',
 'ds140_Cobalt.csv',
 'unoosa_Japan.csv',
 'doe_Lithium-ion battery storageHungary.csv',
 'doe_Pumped hydro storageDenmark.csv',
 'dna_sequencing.csv',
 'doe_Hydrogen storageCanada.csv',
 'unoosa_Monaco.csv',
 'doe_Lithium-ion battery storageGuinea.csv',
 'unoosa_Turkey.csv',
 'doe_Pumped hydro storageSouth Africa.csv',
 'ds140_Tin.csv',
 'Dishwasher.csv',
 'doe_Pumped hydro storageSouth Korea.csv',
 'unoosa_Kazakhstan.csv',
 'ds896_CopperMining.csv',
 'doe_Flow battery storageCanada.csv',
 'Paraxylene.csv',
 'ammonia.csv',
 'unoosa_China.csv',
 'doe_Lithium-ion battery storageUnited States.csv',
 'doe_Pumped hydro storagePoland.csv',
 'unoosa_Malaysia.csv',
 'unoosa_France.csv',
 'doe_Lithium-ion battery storageHaiti.csv',
 'unoosa_Switzerland.csv',
 'doe_Lithium-ion battery storageFinland.csv',
 'vanadium_flow.csv',
 'doe_Lithium-ion battery storageIreland.csv',
 'ashp.csv',
 'doe_Compressed air energy storageNetherlands.csv',
 'unoosa_Kenya.csv',
 'doe_Flow battery storageSouth Africa.csv',
 'unoosa_World.csv',
 'unoosa_Belgium.csv',
 'Running water.csv',
 'desalination.csv',
 'doe_Pumped hydro storageRussia.csv',
 'unoosa_Ghana.csv',
 'doe_Sodium-based battery storageSouth Korea.csv',
 'unoosa_Moldova.csv',
 'chat_Postal Traffic.csv',
 'Power steering.csv',
 'doe_Compressed air energy storageGermany.csv',
 'unoosa_United Arab Emirates.csv',
 'doe_Pumped hydro storageUkraine.csv',
 'fao_Soybean Production.csv',
 'unoosa_Czechia.csv',
 'coal_price.csv',
 'lng_price.csv',
 'doe_Lithium-ion battery storageAustralia.csv',
 "fao_Cow's Milk Production.csv",
 'Microprocessor Clock Speed.csv',
 'Polyester Fiber.csv',
 'ds140_IronOre.csv',
 'doe_Sodium-based battery storageFrench Guiana.csv',
 'doe_Lithium-ion battery storageHong Kong.csv',
 'doe_Lead-acid battery storageGermany.csv',
 'doe_Lithium-ion battery storageSpain.csv',
 'unoosa_Israel.csv',
 'doe_Heat thermal battery storageChile.csv',
 'unoosa_Latvia.csv',
 'doe_Flow battery storageUnited Kingdom.csv',
 'doe_Flywheel battery storageNetherlands.csv',
 'doe_Heat thermal battery storageSouth Africa.csv',
 'ds896_CopperRefining.csv',
 'doe_Nickel-based batteryNetherlands.csv',
 'unoosa_Nigeria.csv',
 'doe_Flow battery storageNew Zealand.csv',
 'cfl_prices.csv',
 'Primary Magnesium.csv',
 'doe_Lithium-ion battery storageCameroon.csv',
 'ds140_RawSteelProduction.csv',
 'solar_pv_global_price.csv',
 'unoosa_Australia.csv',
 'doe_Zinc-based batteryUnited States.csv',
 'unoosa_Bhutan.csv',
 'doe_Lead-acid battery storageUnited States.csv',
 'doe_Compressed air energy storageChina.csv',
 'doe_Latent heat storageIreland.csv',
 'doe_Electro-chemical capacitorSpain.csv',
 'ds140_Graphite.csv',
 'doe_Flow battery storageNetherlands.csv',
 'doe_Hydrogen storageItaly.csv',
 'doe_Pumped hydro storageLithuania.csv',
 'unoosa_Papua New Guinea.csv',
 'csp_price.csv',
 'doe_Pumped hydro storageIndonesia.csv',
 'Styrene.csv',
 'doe_Flow battery storageIsrael.csv',
 'doe_Sodium-based battery storageGermany.csv',
 'unoosa_Canada.csv',
 'ds140_Nickel.csv',
 'fgd_price.csv',
 'doe_Lithium-ion battery storageJordan.csv',
 'doe_Heat thermal battery storageIndia.csv',
 'doe_Lithium-ion battery storageBurkina-Faso.csv',
 'doe_Lithium-ion battery storageQatar.csv',
 'Internet Backbone Bandwidth.csv',
 'doe_Sensible heat storageUnited States.csv',
 'Microwave.csv',
 'doe_Pumped hydro storageTaiwan.csv',
 'Electric Range.csv',
 'unoosa_Peru.csv',
 'doe_Nickel-based batteryJapan.csv',
 'unicef.csv',
 'onshore_tic_country.csv',
 'chat_Television.csv',
 'unoosa_South Korea.csv',
 'doe_Lead-acid battery storageAntarctica.csv',
 'BisphenolA.csv',
 'unoosa_Ecuador.csv',
 'doe_Compressed air energy storageCanada.csv',
 'Disk brakes.csv',
 'doe_Lead-acid battery storageUnited Kingdom.csv',
 'usda.csv',
 'doe_Heat thermal battery storageUnited States.csv',
 'pcdb_Shotgun_Sanger_DNA_Sequencing.csv',
 'doe_Lithium-ion battery storageDenmark.csv',
 'nemet_ccs.csv',
 'doe_Lithium-ion battery storageEgypt.csv',
 'unoosa_Luxembourg.csv',
 'Methanol.csv',
 'unoosa_Nepal.csv',
 'doe_Hydrogen storageThailand.csv',
 'doe_Lithium-ion battery storageNiger.csv',
 'ds140_Lithium.csv',
 'unoosa_Norway.csv',
 'ds896_Lead.csv',
 'unoosa_Mexico.csv',
 'ds140_Salt.csv',
 'doe_Sodium-based battery storageChina.csv',
 'nasa_prices.csv',
 'doe_Sodium-based battery storageAustralia.csv',
 'Motor Gasoline.csv',
 'doe_Flow battery storageKazakhstan.csv',
 'doe_Lead-acid battery storageNew Zealand.csv',
 'doe_Flow battery storageCzech Republic.csv',
 'lead_acid.csv',
 'Random Access Memory.csv',
 'unoosa_Bangladesh.csv',
 'doe_Electro-chemical capacitorUnited States.csv',
 'doe_Flow battery storageUnited States.csv',
 'doe_Heat thermal battery storageUnited Kingdom.csv',
 'doe_Lithium-ion battery storageCanada.csv',
 'doe_Nickel-based batteryQatar.csv',
 'unoosa_Jordan.csv',
 'doe_Flywheel battery storageAntarctica.csv',
 'doe_Pumped hydro storageBrazil.csv',
 'Urea.csv',
 'unoosa_Hungary.csv',
 'doe_Pumped hydro storageGreece.csv',
 'fao.csv',
 'Flush toilet.csv',
 'Automatic transmission.csv',
 'doe_Lithium-ion battery storageChile.csv',
 'doe_Heat thermal battery storageSpain.csv',
 'doe_Zinc-based batteryMadagascar.csv',
 'doe_Sodium-based battery storageEquatorial Guinea.csv',
 'Neoprene Rubber.csv',
 'doe_Electro-chemical capacitorItaly.csv',
 'Hydrofluoric Acid.csv',
 'unoosa_Bolivia.csv',
 'doe_Sodium-based battery storageGreece.csv',
 'doe_Pumped hydro storageChina.csv',
 'doe_Flywheel battery storageSpain.csv',
 'solar_pv_tic_country.csv.csv',
 'doe_Lead-acid battery storageKenya.csv',
 'doe_Lithium-ion battery storageSaudi Arabia.csv',
 'Sodium.csv',
 'gshp.csv',
 'doe_Lithium-ion battery storageJapan.csv',
 'cisco.csv',
 'doe_Lithium-ion battery storageMartinique.csv',
 'pumped_hydro.csv',
 'Internet.csv',
 'unoosa_Costa Rica.csv',
 'Ethanolamine.csv',
 'unoosa_Armenia.csv',
 'doe_Lead-acid battery storageVanuatu.csv',
 'doe_Pumped hydro storageBelgium.csv',
 'doe_Flow battery storageIndonesia.csv',
 'ds896_IronOre.csv',
 'ds140_RareEarth.csv',
 'Ethylene.csv',
 'doe_Pumped hydro storagePhilippines.csv',
 'chat_Passenger Vehicles.csv',
 'doe_Lithium-ion battery storageFrance.csv',
 'ds140_SandGravelIndustrial.csv',
 'dot.csv',
 'doe_Lithium-ion battery storageNetherlands.csv',
 'doe_Sensible heat storageUnited Arab Emirates.csv',
 'doe_Sodium-based battery storageMaldives.csv',
 'doe_Zinc-based batteryIndonesia.csv',
 'unoosa_Guatemala.csv',
 'doe_Lead-acid battery storageMadagascar.csv',
 'unoosa_Argentina.csv',
 'unoosa_Algeria.csv',
 'doe_Flow battery storageFrench Polynesia.csv',
 'chat_Radio.csv',
 'unoosa_South Africa.csv',
 'Formaldehyde.csv',
 'Sodium Chlorate.csv',
 'fao_Cotton Seed Production.csv',
 'wet_fgd_systems.csv',
 'doe_Flow battery storageChina.csv',
 'doe_Pumped hydro storageIran.csv',
 'doe_Lithium-ion battery storageItaly.csv',
 'doe_Lithium-ion battery storagePhilippines.csv',
 'doe_Lithium-ion battery storageNew Zealand.csv',
 'canals.csv',
 'doe_Lithium-ion battery storageGermany.csv',
 'unoosa_Azerbaijan.csv',
 'unoosa_Venezuela.csv',
 'Benzene.csv',
 'bioenergy_price.csv',
 'doe_Electro-chemical capacitorIreland.csv',
 'doe_Sensible heat storageChina.csv',
 'doe_Latent heat storageUnited States.csv',
 'doe_Lead-acid battery storageIreland.csv',
 'doe_Sensible heat storageIsrael.csv',
 'unoosa_North Korea.csv',
 'geothermal_lcoe.csv',
 'doe_Lead-acid battery storageCape Verde.csv',
 'unoosa_Estonia.csv',
 'Polystyrene.csv',
 'doe_Pumped hydro storageUnited States.csv',
 'Phenol.csv',
 'offshore_wind_total_installed_cost.csv',
 'doe_Lithium-ion battery storageIndia.csv',
 'chat_Telegraph Traffic.csv',
 'Maleic Anhydride.csv',
 'Amazon Prime users.csv',
 'unoosa_Tunisia.csv',
 'unoosa_Ukraine.csv',
 'unoosa_Turkmenistan.csv',
 'eia.csv',
 'unoosa_Colombia.csv',
 'geothermal_total_installed_cost.csv']

In [78]:
csv = []
for file in clean_files:
    if '.csv' in file:
        name = 'cleaned_data/' + file
        csv.append(name)

In [79]:
frame = pd.read_csv(clean_data_file_path+'/frame.csv')
frame

Empty DataFrame
Columns: [ID, Spatial Scale, Country Code, Country Name, Technology Name, Metric, Unit, Data Source, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, ...]
Index: []

[0 rows x 334 columns]

In [80]:
locale.setlocale(locale.LC_NUMERIC, '')

'C'

In [81]:
# don't use default na, this erroneously converts 'NA' (iso code for Namibia) to a missing value
# I manually input all the default na vals except for 'NA' to prevent this
# https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html
df_list = [frame]
for file in csv:
    file = pd.read_csv(file, thousands=',',keep_default_na=False, 
                       na_values=['-1.#IND', '1.#QNAN', '1.#IND', '-1.#QNAN', '#N/A N/A', '#N/A', 'N/A', 'n/a', 
                                  '<NA>', '#NA', 'NULL', 'null', 'NaN', '-NaN', 'nan', '-nan', 'None', ''])
    df_list.append(file)

In [82]:
all_tech_df = pd.concat(df_list)
all_tech_df

/var/folders/cy/xd4mmw610b3cr6tjgv0h8hlr0000gn/T/ipykernel_5038/520162873.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_tech_df = pd.concat(df_list)

,ID,Spatial Scale,Country Code,Country Name,Technology Name,Metric,Unit,Data Source,1700,1701,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 0
0,Lithium-Ion Battery Storage_Cumulative Rated P...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Power,kW,GESDB,NaN,NaN,...,1.900000e+02,2.900000e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lithium-Ion Battery Storage_Cumulative Rated C...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Capacity,kWh,GESDB,NaN,NaN,...,7.600000e+02,1.160000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Sensible Heat Storage_Cumulative Rated Power_ZA,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Power,kW,GESDB,NaN,NaN,...,3.550000e+05,4.550000e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sensible Heat Storage_Cumulative Rated Capacit...,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Capacity,kWh,GESDB,NaN,NaN,...,1.745000e+06,2.945000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Onshore Wind Energy_Levelized Cost of Energy_DK,National,DK,Denmark,Onshore Wind Energy,Levelized Cost of Energy,2022 USD/kWh,IRENA,NaN,NaN,...,4.898293e-02,4.679236e-02,0.048501,0.042769,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,Objects Launched Into Space_Total Number_UA,National,UA,Ukraine,Objects Launched Into Space,Total Number,-,UNOOSA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
0,Objects Launched Into Space_Total Number_TM,National,TM,Turkmenistan,Objects Launched Into Space,Total Number,-,UNOOSA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Liquefied Natural Gas_Annual Production_US,National,US,United States,Liquefied Natural Gas,Annual Production,billion cubic feet,EIA,NaN,NaN,...,7.075400e+02,1.083120e+03,1819.400000,2389.840000,3560.820000,NaN,NaN,NaN,NaN,NaN
0,Objects Launched Into Space_Total Number_CO,National,CO,Colombia,Objects Launched Into Space,Total Number,-,UNOOSA,NaN,NaN,...,NaN,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Geothermal Energy_Total Installed Cost_World,Global,World,World,Geothermal Energy,Total Installed Cost,2022 USD/kW,IRENA,NaN,NaN,...,4.294267e+03,4.657604e+03,4414.770041,3726.247383,4269.700034,NaN,NaN,NaN,NaN,NaN

In [83]:
len(set(all_tech_df['Technology Name']))

252

In [84]:
for x in set(all_tech_df['Technology Name']):
    print((x))

HEPBB Vaccine
ROTAC Vaccine
Air Conditioning Machines
Pentaerythritol
Videocassette Recorder
Cotton Seed Production
Shotgun Sanger DNA Sequencing
DTP3 Vaccine
Polyvinylchloride
Zinc Production
Nickel-Metal Hydride Battery
Marine Energy
Biofuels Production
Water Heater
Copper|Refining
DTP1 Vaccine
Compressed Air Energy Storage
Renewable Power
Fluid Catalytic Cracking Refineries
Cement
Cable TV
Phosphate Fertilizer
Household Refrigerators and Freezers
Sand and Gravel|Industrial
Concentrating Solar Power
Power Steering
Laundry Dryers
Capillary DNA Sequencing
Bicycles and Other Cycles
Telephones and Videophones
Pumped Hydropower
Nickel-Based Battery
Cyclohexane
Flow Battery Storage
Nuclear Weapons
Flush Toilet
POL3 Vaccine
Colour TV
Ethylene
Ebook Reader
High-Speed Rail
Cow's Milk Production
Turbo-Jets of a Thrust Not Exceeding 25 kN
Caprolactam
Nitric Acid
Internet Backbone Bandwidth
High-Density Polyethylene
Geothermal Energy
Electro-Chemical Capacitor
Household Internet Access
Vacuums
Oil Production
Compact Fluorescent Light Bulbs
Sodium-Sulphur Battery
Bioenergy
Insect-Resistant Corn
Styrene
Nitrogen Fertilizer
Insect-Resistant Cotton
Solar Photovoltaic
Maleic Anhydride
Vinyl Chloride
Sulphuric Acid
Electronic Ignition
Television
Herbicide-Tolerant Cotton
Steamships
Benzene
Flue Gas Desulphurization (Wet and Dry)
Primary Magnesium
Copper|Mining
DNA Sequencing (All Methods)
CFLs
Tin
Smartphone Usage
Solid Biofuels
Space Launches
Random Access Memory
Telephones
Natural Gas Pipeline
Synthetic Filament Tow and Staple Fibers
Processor Performance
HEPB3 Vaccine
Lithium Mine Production
Natural Gas Power
Electric Range
Home Air Conditioning
Nitrogenous Fertilizers
Salt Production
Electric Water Heaters and Immersion Heaters
Oil Pipeline
Nickel
Running Water
Paraxylene
Passenger Cars
Primary Copper
Washing Machines
Hydroelectricity
Railroad
Primary Bauxite Production
MCV2 Vaccine
Pumped Hydro Storage
Canals
Neoprene Rubber
Cadmium Refining
Steam Locomotives
Silver
Postal Traffic
Nickel Production
Electric Bicycles
Soybean Production
Refined Copper
Refrigerators
Liquid Biofuels
Jet Aircraft
Magnetic Data Storage
Liquefied Natural Gas
IPV1 Vaccine
Microwaves
Freezer
Coal Production
Dishwashers
Internet Traffic
Hydropower Mega-Dams
Vacuum Cleaners
Phthalic Anhydride
Objects Launched Into Space
BisphenolA
Disk Brakes
Lithium-Ion Battery Storage
Hydropower
Cobalt
Magnesium
Silver Production
Methanol
Motorcycles and Scooters
Offshore Wind Energy
BCG Vaccine
Automatic Transmission
Podcasting
Air-Source Heat Pumps
Polyester Fiber
Biogas
Acrylonitrile
Social Media Usage
Potash Fertilizer
Tablet
Telegraph Traffic
Rare Earth Mine Production
Electricity
Primary Aluminum Production
Sand and Gravel|Construction
Ethylene Glycol
Sensible Heat Storage
Crude Petroleum
Ethanol
Nox Pollution Controls (Boilers)
Natural Gas Production
Sodium
Lithium-Ion Cells
Lead
Computing Growth
Passenger Vehicles
Crop Harvester
Low-Density Polyethylene
Titanium Sponge
Cellphones
Sodium Chlorate
Central Heating
Home Computers
Transistors per Microprocessor
Households With Only Mobile Phones (No Landlines)
Stove
Potassic Fertilizers
Corn Production
Iron
Carbon Capture and Sequestration
Herbicide-Tolerant Soybeans
PCV3 Vaccine
Amazon Prime Users
Sugar Cane Production
MCV1 Vaccine
RCV1 Vaccine
Raw Steel Production
Urea
Tin Production
Sugar Output
Ammonia Synthesis
Motor Gasoline
Polystyrene
Real-Time Gross Settlement Adoption
Graphite
Aniline
Hydrofluoric Acid
Microcomputers
Latent Heat Storage
Beer Production
Milk
Hydrochloric Acid
Flywheel Battery Storage
Nuclear Energy
Acrylic Fiber
Vanadium Redox-Flow Battery
Microprocessor Clock Speed
Television Receivers
Hydrogen Storage
Artificial and Synthetic Fibers
Solar Thermal Energy
Radial Tires
HIB3 Vaccine
Desalination Capacity
Radio
Public Roads
Coal Power
Iron Ore
Gold Production
Herbicide-Tolerant Corn
Concentrated Solar Power
Submarine Cables
Sodium-Based Battery Storage
Household Washing and Drying Machines
Caustic Soda
Onshore Wind Energy
Bicycles
Combined Refrigerators-Freezers
Shale Production
Heat Thermal Battery Storage
Zinc
Ethanolamine
YFV Vaccine
Beer
Formaldehyde
Ground Source Heat Pumps
Phenol
Synthetic Filament Yarn
Capture Fisheries
Wet Flue Gas Desulfurization Systems
Oil Refining Capacity
Microwave Ovens
Lead-Acid Battery Storage
Radio Receivers
Cars
Caustic Soda Acid
Aquaculture Production
Zinc-Based Battery
Lead-Acid Battery
Motorcycles
Stationary Steam Engines
Liquefied Natural Gas (LNG)
Gold
Vinyl Acetate
Crude Oil

In [85]:
all_tech_df[all_tech_df['Technology Name']=='Bicycles']

,ID,Spatial Scale,Country Code,Country Name,Technology Name,Metric,Unit,Data Source,1700,1701,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 0
2,Bicycles_Cumulative Total Capacity_World,Global,World,World,Bicycles,Cumulative Total Capacity,MW,Wilson & Grubler,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
#all_tech_df['Technology Name'] = all_tech_df['Technology Name'].str.title()

In [87]:
all_tech_df.insert(8, 'Long Technology Name', all_tech_df['Metric'] + '|' + all_tech_df['Technology Name'])
all_tech_df

/var/folders/cy/xd4mmw610b3cr6tjgv0h8hlr0000gn/T/ipykernel_5038/4289715991.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all_tech_df.insert(8, 'Long Technology Name', all_tech_df['Metric'] + '|' + all_tech_df['Technology Name'])

,ID,Spatial Scale,Country Code,Country Name,Technology Name,Metric,Unit,Data Source,Long Technology Name,1700,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 0
0,Lithium-Ion Battery Storage_Cumulative Rated P...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Power,kW,GESDB,Cumulative Rated Power|Lithium-Ion Battery Sto...,NaN,...,1.900000e+02,2.900000e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lithium-Ion Battery Storage_Cumulative Rated C...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Capacity,kWh,GESDB,Cumulative Rated Capacity|Lithium-Ion Battery ...,NaN,...,7.600000e+02,1.160000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Sensible Heat Storage_Cumulative Rated Power_ZA,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Power,kW,GESDB,Cumulative Rated Power|Sensible Heat Storage,NaN,...,3.550000e+05,4.550000e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sensible Heat Storage_Cumulative Rated Capacit...,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Capacity,kWh,GESDB,Cumulative Rated Capacity|Sensible Heat Storage,NaN,...,1.745000e+06,2.945000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Onshore Wind Energy_Levelized Cost of Energy_DK,National,DK,Denmark,Onshore Wind Energy,Levelized Cost of Energy,2022 USD/kWh,IRENA,Levelized Cost of Energy|Onshore Wind Energy,NaN,...,4.898293e-02,4.679236e-02,0.048501,0.042769,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,Objects Launched Into Space_Total Number_UA,National,UA,Ukraine,Objects Launched Into Space,Total Number,-,UNOOSA,Total Number|Objects Launched Into Space,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
0,Objects Launched Into Space_Total Number_TM,National,TM,Turkmenistan,Objects Launched Into Space,Total Number,-,UNOOSA,Total Number|Objects Launched Into Space,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Liquefied Natural Gas_Annual Production_US,National,US,United States,Liquefied Natural Gas,Annual Production,billion cubic feet,EIA,Annual Production|Liquefied Natural Gas,NaN,...,7.075400e+02,1.083120e+03,1819.400000,2389.840000,3560.820000,NaN,NaN,NaN,NaN,NaN
0,Objects Launched Into Space_Total Number_CO,National,CO,Colombia,Objects Launched Into Space,Total Number,-,UNOOSA,Total Number|Objects Launched Into Space,NaN,...,NaN,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Geothermal Energy_Total Installed Cost_World,Global,World,World,Geothermal Energy,Total Installed Cost,2022 USD/kW,IRENA,Total Installed Cost|Geothermal Energy,NaN,...,4.294267e+03,4.657604e+03,4414.770041,3726.247383,4269.700034,NaN,NaN,NaN,NaN,NaN

In [88]:
all_tech_df.reset_index(drop=True,inplace=True)
all_tech_df

,ID,Spatial Scale,Country Code,Country Name,Technology Name,Metric,Unit,Data Source,Long Technology Name,1700,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 0
0,Lithium-Ion Battery Storage_Cumulative Rated P...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Power,kW,GESDB,Cumulative Rated Power|Lithium-Ion Battery Sto...,NaN,...,1.900000e+02,2.900000e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lithium-Ion Battery Storage_Cumulative Rated C...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Capacity,kWh,GESDB,Cumulative Rated Capacity|Lithium-Ion Battery ...,NaN,...,7.600000e+02,1.160000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sensible Heat Storage_Cumulative Rated Power_ZA,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Power,kW,GESDB,Cumulative Rated Power|Sensible Heat Storage,NaN,...,3.550000e+05,4.550000e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Sensible Heat Storage_Cumulative Rated Capacit...,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Capacity,kWh,GESDB,Cumulative Rated Capacity|Sensible Heat Storage,NaN,...,1.745000e+06,2.945000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Onshore Wind Energy_Levelized Cost of Energy_DK,National,DK,Denmark,Onshore Wind Energy,Levelized Cost of Energy,2022 USD/kWh,IRENA,Levelized Cost of Energy|Onshore Wind Energy,NaN,...,4.898293e-02,4.679236e-02,0.048501,0.042769,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8507,Objects Launched Into Space_Total Number_UA,National,UA,Ukraine,Objects Launched Into Space,Total Number,-,UNOOSA,Total Number|Objects Launched Into Space,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
8508,Objects Launched Into Space_Total Number_TM,National,TM,Turkmenistan,Objects Launched Into Space,Total Number,-,UNOOSA,Total Number|Objects Launched Into Space,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8509,Liquefied Natural Gas_Annual Production_US,National,US,United States,Liquefied Natural Gas,Annual Production,billion cubic feet,EIA,Annual Production|Liquefied Natural Gas,NaN,...,7.075400e+02,1.083120e+03,1819.400000,2389.840000,3560.820000,NaN,NaN,NaN,NaN,NaN
8510,Objects Launched Into Space_Total Number_CO,National,CO,Colombia,Objects Launched Into Space,Total Number,-,UNOOSA,Total Number|Objects Launched Into Space,NaN,...,NaN,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8511,Geothermal Energy_Total Installed Cost_World,Global,World,World,Geothermal Energy,Total Installed Cost,2022 USD/kW,IRENA,Total Installed Cost|Geothermal Energy,NaN,...,4.294267e+03,4.657604e+03,4414.770041,3726.247383,4269.700034,NaN,NaN,NaN,NaN,NaN

In [89]:
omit = []
for col in all_tech_df.columns:
    if len(col) != 4 or col == 'Unit':
         omit.append(col)
empty_rows = all_tech_df.drop(columns=omit)
empty_rows.dropna(how='all', inplace=True)
na_idx = []
for idx in all_tech_df.index:
    if idx not in empty_rows.index:
        na_idx.append(idx)
all_tech_df.drop(na_idx, inplace=True)
all_tech_df

,ID,Spatial Scale,Country Code,Country Name,Technology Name,Metric,Unit,Data Source,Long Technology Name,1700,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 0
0,Lithium-Ion Battery Storage_Cumulative Rated P...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Power,kW,GESDB,Cumulative Rated Power|Lithium-Ion Battery Sto...,NaN,...,1.900000e+02,2.900000e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lithium-Ion Battery Storage_Cumulative Rated C...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Capacity,kWh,GESDB,Cumulative Rated Capacity|Lithium-Ion Battery ...,NaN,...,7.600000e+02,1.160000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sensible Heat Storage_Cumulative Rated Power_ZA,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Power,kW,GESDB,Cumulative Rated Power|Sensible Heat Storage,NaN,...,3.550000e+05,4.550000e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Sensible Heat Storage_Cumulative Rated Capacit...,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Capacity,kWh,GESDB,Cumulative Rated Capacity|Sensible Heat Storage,NaN,...,1.745000e+06,2.945000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Onshore Wind Energy_Levelized Cost of Energy_DK,National,DK,Denmark,Onshore Wind Energy,Levelized Cost of Energy,2022 USD/kWh,IRENA,Levelized Cost of Energy|Onshore Wind Energy,NaN,...,4.898293e-02,4.679236e-02,0.048501,0.042769,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8507,Objects Launched Into Space_Total Number_UA,National,UA,Ukraine,Objects Launched Into Space,Total Number,-,UNOOSA,Total Number|Objects Launched Into Space,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
8508,Objects Launched Into Space_Total Number_TM,National,TM,Turkmenistan,Objects Launched Into Space,Total Number,-,UNOOSA,Total Number|Objects Launched Into Space,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8509,Liquefied Natural Gas_Annual Production_US,National,US,United States,Liquefied Natural Gas,Annual Production,billion cubic feet,EIA,Annual Production|Liquefied Natural Gas,NaN,...,7.075400e+02,1.083120e+03,1819.400000,2389.840000,3560.820000,NaN,NaN,NaN,NaN,NaN
8510,Objects Launched Into Space_Total Number_CO,National,CO,Colombia,Objects Launched Into Space,Total Number,-,UNOOSA,Total Number|Objects Launched Into Space,NaN,...,NaN,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8511,Geothermal Energy_Total Installed Cost_World,Global,World,World,Geothermal Energy,Total Installed Cost,2022 USD/kW,IRENA,Total Installed Cost|Geothermal Energy,NaN,...,4.294267e+03,4.657604e+03,4414.770041,3726.247383,4269.700034,NaN,NaN,NaN,NaN,NaN

In [90]:
#all_tech_df['Metric'] = all_tech_df['Metric'].str.title()

In [91]:
all_tech_df['Metric'] = all_tech_df['Metric'].str.strip()

In [92]:
set(all_tech_df['Metric'])

{'Annual Production',
 'Annual production',
 'Average Capacity of Unit Additions',
 'Computing Capacity',
 'Cumulative Acreage',
 'Cumulative Length',
 'Cumulative Rated Capacity',
 'Cumulative Rated Power',
 'Cumulative Total Capacity',
 'Installed Capacity',
 'Installed electricity capacity',
 'Levelized Cost of Energy',
 'Net Total Capacity',
 'Price',
 'Share of Boilers',
 'Share of Households',
 'Share of Market',
 'Share of Population',
 'Total Capacity',
 'Total Installed Cost',
 'Total Length',
 'Total Number'}

In [93]:
all_tech_df.to_csv('all_tech_version 2.0.csv', index=False)

In [94]:
all_tech_df = all_tech_df[all_tech_df['Metric']!='Price']
all_tech_df = all_tech_df[all_tech_df['Metric']!='Cost']

all_tech_df

,ID,Spatial Scale,Country Code,Country Name,Technology Name,Metric,Unit,Data Source,Long Technology Name,1700,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 0
0,Lithium-Ion Battery Storage_Cumulative Rated P...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Power,kW,GESDB,Cumulative Rated Power|Lithium-Ion Battery Sto...,NaN,...,1.900000e+02,2.900000e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lithium-Ion Battery Storage_Cumulative Rated C...,National,TG,Togo,Lithium-Ion Battery Storage,Cumulative Rated Capacity,kWh,GESDB,Cumulative Rated Capacity|Lithium-Ion Battery ...,NaN,...,7.600000e+02,1.160000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sensible Heat Storage_Cumulative Rated Power_ZA,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Power,kW,GESDB,Cumulative Rated Power|Sensible Heat Storage,NaN,...,3.550000e+05,4.550000e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Sensible Heat Storage_Cumulative Rated Capacit...,National,ZA,South Africa,Sensible Heat Storage,Cumulative Rated Capacity,kWh,GESDB,Cumulative Rated Capacity|Sensible Heat Storage,NaN,...,1.745000e+06,2.945000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Onshore Wind Energy_Levelized Cost of Energy_DK,National,DK,Denmark,Onshore Wind Energy,Levelized Cost of Energy,2022 USD/kWh,IRENA,Levelized Cost of Energy|Onshore Wind Energy,NaN,...,4.898293e-02,4.679236e-02,0.048501,0.042769,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8507,Objects Launched Into Space_Total Number_UA,National,UA,Ukraine,Objects Launched Into Space,Total Number,-,UNOOSA,Total Number|Objects Launched Into Space,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
8508,Objects Launched Into Space_Total Number_TM,National,TM,Turkmenistan,Objects Launched Into Space,Total Number,-,UNOOSA,Total Number|Objects Launched Into Space,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8509,Liquefied Natural Gas_Annual Production_US,National,US,United States,Liquefied Natural Gas,Annual Production,billion cubic feet,EIA,Annual Production|Liquefied Natural Gas,NaN,...,7.075400e+02,1.083120e+03,1819.400000,2389.840000,3560.820000,NaN,NaN,NaN,NaN,NaN
8510,Objects Launched Into Space_Total Number_CO,National,CO,Colombia,Objects Launched Into Space,Total Number,-,UNOOSA,Total Number|Objects Launched Into Space,NaN,...,NaN,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8511,Geothermal Energy_Total Installed Cost_World,Global,World,World,Geothermal Energy,Total Installed Cost,2022 USD/kW,IRENA,Total Installed Cost|Geothermal Energy,NaN,...,4.294267e+03,4.657604e+03,4414.770041,3726.247383,4269.700034,NaN,NaN,NaN,NaN,NaN

In [95]:
all_tech_df.to_csv('all_tech_version_1.5.csv', index=False)

In [ ]:
# no_country = []
# for tech in set(all_tech_df['Technology Name']):
#     countries = list(set(all_tech_df[all_tech_df['Technology Name'] == tech]['Country Name']))
#     id_ = list(all_tech_df[all_tech_df['Technology Name'] == tech]['ID'])
#     if len(countries) <= 2:
#         no_country.extend(id_)

In [ ]:
# all_tech_w_countrylvl = all_tech_df.set_index('ID', drop=True)
# all_tech_w_countrylvl.drop(index=no_country, inplace=True)
# all_tech_w_countrylvl

In [ ]:
# all_tech_w_countrylvl.to_csv('all_tech_with_country-level.csv', index=False)