In [1]:
import os
import pandas as pd
from pandas import Series, DataFrame
import country_converter as coco

In [2]:
# https://www.jstor.org/stable/1927670
# digitized from Table A (p. 150)

In [3]:
os.chdir('/Users/ariana/desktop/historical_tech')

In [4]:
canals = pd.read_excel('raw data/canals.xlsx', header=1, index_col=0, usecols=[0,2])
canals.dropna(how='all', inplace=True)
canals = canals.transpose()
canals.columns.name = None
canals['Country Name'] = 'United States'
canals['Country Code'] = 'US'
canals['Spatial Scale'] = 'National'
canals['Unit'] = 'miles'
canals['Data Source'] = 'Isard'
canals['Technology Name'] = 'Canals'
canals['Metric'] = 'Total Length'
canals['ID'] = canals['Technology Name'] + '_' + canals['Metric'] + '_' + canals['Country Code']
canals.set_index('ID', drop=True, inplace=True)
canals.to_csv('cleaned data/canals.csv')
canals

,1794,1802,1804,1819,1821,1825,1826,1827,1828,1829,...,1859,1860,1861,Country Name,Country Code,Spatial Scale,Unit,Data Source,Technology Name,Metric
ID,,,,,,,,,,,,,,,,,,,,,
Canals_Total Length_US,30,52,79,155,203,625,687,772,943,1029,...,4246,4254,4261,United States,US,National,miles,Isard,Canals,Total Length