In [1]:
import os
import pandas as pd
from pandas import Series, DataFrame
import country_converter as coco
import numpy as np
import copy

In [2]:
# https://sandia.gov/ess-ssl/gesdb/public/statistics.html

In [3]:
path = '/Users/ariana/desktop/historical_tech'
os.chdir(path)

In [4]:
doe = pd.read_csv('raw data/Cummulative Sum by Year_Full Data_data.csv', usecols=[0,1,2,9,10])
doe = doe.drop_duplicates()
doe

,Year of Project Year,Technology Mid-Type,Country,Rated Capacity (kWh),Rated Power (kW)
0,2007,Technology Mid-Type Unknown,United States,32000.0,64000
1,2009,Technology Mid-Type Unknown,Sweden,NaN,10000
2,2011,Technology Mid-Type Unknown,United States,NaN,430
3,2011,Technology Mid-Type Unknown,United States,NaN,1500
4,2013,Technology Mid-Type Unknown,Spain,NaN,0
...,...,...,...,...,...
1620,2018,Pumped hydro storage,Indonesia,NaN,1040000
1621,2019,Pumped hydro storage,Australia,1500000.0,250000
1622,2020,Pumped hydro storage,Ireland,9000.0,1500
1623,2020,Pumped hydro storage,Japan,NaN,200000
1624,2020,Pumped hydro storage,Japan,NaN,1880000

In [5]:
doe.replace({'Lithium-ion battery':'Lithium-ion battery storage', 'Latent heat':'Latent heat storage', 
             'Sensible heat':'Sensible heat storage','Flow battery':'Flow battery storage',
             'Sodium-based battery':'Sodium-based battery storage',
             'Heat thermal storage':'Heat thermal battery storage',
             'Lead-acid battery':'Lead-acid battery storage','Flywheel':'Flywheel battery storage'}, inplace=True)

In [6]:
tech_list = sorted(list(set(doe['Technology Mid-Type'])))
tech_list.remove('Technology Mid-Type Unknown')
tech_list

['Compressed air energy storage',
 'Electro-chemical capacitor',
 'Flow battery storage',
 'Flywheel battery storage',
 'Heat thermal battery storage',
 'Hydrogen storage',
 'Latent heat storage',
 'Lead-acid battery storage',
 'Lithium-ion battery storage',
 'Nickel-based battery',
 'Pumped hydro storage',
 'Sensible heat storage',
 'Sodium-based battery storage',
 'Zinc-based battery']

In [7]:
df = doe[(doe['Technology Mid-Type'] == 'Compressed air energy storage') & (doe['Country'] == 'United States')]
df

,Year of Project Year,Technology Mid-Type,Country,Rated Capacity (kWh),Rated Power (kW)
1188,1991,Compressed air energy storage,United States,2860000.0,110000
1189,2012,Compressed air energy storage,United States,500000.0,2000
1192,2013,Compressed air energy storage,United States,30432000.0,317000
1193,2013,Compressed air energy storage,United States,60.0,80
1194,2013,Compressed air energy storage,United States,1500.0,1500
1198,2015,Compressed air energy storage,United States,NaN,0
1203,2020,Compressed air energy storage,United States,3000000.0,300000

In [8]:
def read_doe(tech_name):
    df = doe[doe['Technology Mid-Type'] == tech_name]
    country_list = list(set(df['Country']))
    for country in country_list:
        df_country = df[df['Country']== country]
        df_country.reset_index(drop=True, inplace=True)
        years = sorted(list(set(df_country['Year of Project Year'])))
        year_dict = {}
        for year in years:
            year_dict[year] = []
        power_dict = copy.deepcopy(year_dict)
        capacity_dict = copy.deepcopy(year_dict)
        for idx in df_country.index:
            power = df_country['Rated Power (kW)'].iloc[idx]
            capacity = df_country['Rated Capacity (kWh)'].iloc[idx]
            year = df_country['Year of Project Year'].iloc[idx]
            power_dict[year].append(power)
            capacity_dict[year].append(capacity)
        power_by_year = []
        for year in power_dict:
            power_by_year.append(np.nansum(power_dict[year]))
        capacity_by_year = []
        for year in capacity_dict:
            capacity_by_year.append(np.nansum(capacity_dict[year]))
        new_df = pd.DataFrame(power_by_year, years)
        new_df[0] = new_df[0].cumsum()
        new_df['Cumulative Rated Capacity'] = capacity_by_year
        new_df['Cumulative Rated Capacity'] = new_df['Cumulative Rated Capacity'].cumsum()
        new_df = new_df.transpose()
        new_df['Technology Name'] = tech_name.title()
        new_df['Country Name'] = country
        new_df['Unit'] = ['kW', 'kWh']
        new_df['Data Source'] = 'GESDB'
        new_df['Metric'] = ['Cumulative Rated Power', 'Cumulative Rated Capacity']
        new_df['Spatial Scale'] = 'National'
        new_df['Country Code'] = coco.convert(names=country, to='iso2')
        new_df['ID'] = new_df['Technology Name'] + '_' + new_df['Metric'] + '_' + new_df['Country Code']
        new_df.set_index('ID', drop=True, inplace=True)
        file_name = 'cleaned data/doe_' + tech_name + country + '.csv'
        new_df.to_csv(file_name)

In [9]:
for tech in tech_list:
    read_doe(tech)